global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'apache'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9117' ]

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:3000' ]

  - job_name: 'influxdb'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:8086' ]

  - job_name: 'alertmanager'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9093' ]

  - job_name: 'elasticsearch'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9200' ]